### ISSUE TITLE
Authorization issues

### ISSUE THREAD

**Issue by jdrews** [alertedsnake/python-ecobee#1]
I am attempting to authorize my ecobee api. It just says "Waiting for user to authorize application.". I'm expecting it to give me an authorization code...

The steps I took: 

```
>>> import ecobee
>>> APIKEY = "REDACTED"
>>> eapi = ecobee.Client(APIKEY,scope='smartRead')
>>> eapi.authorize_start()
Waiting for user to authorize application.
```

My app on ecobee app is set to Authorization method: ecobee PIN

**Comment by alertedsnake** [comment]
I just added a fix for this problem.  Remove your authentication cache file (usually ~/.config/ecobee) and try again.

**Comment by jdrews** [comment]
I upgraded my copy of python-ecobee and deleted the ecobee.db in my .config. I then reran the following steps I listed above. I get the same result. 

I confirmed `self.auth.token_type = None` is on line 170 of my `__init__.py`

```
root@bitmaker1:~# python3
Python 3.4.2 (default, Oct  8 2014, 10:45:20)
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ecobee
>>> APIKEY = "REDACTED"
>>> eapi = ecobee.Client(APIKEY,scope='smartRead')
>>> eapi.authorize_start()
Waiting for user to authorize application.
>>>

```

**Comment by alertedsnake** [comment]
That output looks fine - did you go into the Ecobee web UI to authorize the application?  You may have to delete the saved credential file and start over.

**Comment by jdrews** [comment]
The ecobee webpage is expecting an authorization code, which as shown above never gets returned to me. Maybe I'm missing something? 

![screenshot_042116_093039_pm](https://cloud.githubusercontent.com/assets/172766/14729062/46af865e-0808-11e6-9987-367e19c8e340.jpg)

**Comment by alertedsnake** [comment]
I had this happen the other day.  Deleted the cached ~/.config/ecobee and
all config in the Ecobee UI, recreated it all, and it went away.  This was
the related to my most recent commit also.

Beyond that, I'd need to be able to reproduce your problem to really be
able to work on solving it.

**Comment by jdrews** [comment]
I figured out what is going on. `self.log.info` is not logging. I discovered this by stepping through with IntelliJ's Python Debugger and noticing that the info logs aren't printing. I was able to extract the value of `result['ecobeePin']` from the debugger and punch that into the Ecobee Web GUI. Now it's synced up but 
`thermostats = eapi.list_thermostats()`
 is throwing 
`ecobee.EcobeeException: 9: Invalid selection. No thermostats in selection. Ensure permissions and selection.`

I'm not sure why it doesn't output anything on my Debian 8 box with Python 3.4.2 and also on Windows 10 with Python 3.5.1...

**Comment by jdrews** [comment]
Python Code:

``` python
APIKEY = "REDACTED"
eapi = ecobee.Client(APIKEY,scope='smartRead')
thermostats = eapi.list_thermostats()
print("thermostats = " + str(thermostats))
```

Stacktrace Error:

```
9: Invalid selection. No thermostats in selection. Ensure permissions and selection.
Traceback (most recent call last):
  File "E:/git/temptrak/random-python-scripts/ecobeeLogger.py", line 9, in <module>
    thermostats = eapi.list_thermostats()
  File "C:\Program Files (x86)\Python\Python35-32\lib\site-packages\ecobee\__init__.py", line 424, in list_thermostats
    self.update()
  File "C:\Program Files (x86)\Python\Python35-32\lib\site-packages\ecobee\__init__.py", line 255, in update
    "includeEvents":            includeEvents,
  File "C:\Program Files (x86)\Python\Python35-32\lib\site-packages\ecobee\__init__.py", line 445, in get
    self._handle_error(r)
  File "C:\Program Files (x86)\Python\Python35-32\lib\site-packages\ecobee\__init__.py", line 491, in _handle_error
    raise EcobeeException(errmsg)
ecobee.EcobeeException: 9: Invalid selection. No thermostats in selection. Ensure permissions and selection.
```

**Comment by jdrews** [comment]
Further testing. I have modified my code to use your exact example in the Readme.md. I get the same results. 

Note the API key and thermostat ID have been redacted

``` python
import ecobee

APIKEY = "REDACTED"

eapi = ecobee.Client(APIKEY)
eapi.update()
t = eapi.get_thermostat("000000000001")
hvacMode = t.settings.get('hvacMode')
print("hvacMode = " + str(hvacMode))

s = t.get_sensor('ei:0')
print('{}: {}°F'.format(s.name, s.temperature))
```

```
9: Invalid selection. No thermostats in selection. Ensure permissions and selection.
Traceback (most recent call last):
  File "E:/git/temptrak/random-python-scripts/ecobeeLogger_simplified.py", line 6, in <module>
    eapi.update()
  File "C:\Program Files (x86)\Python\Python35-32\lib\site-packages\ecobee\__init__.py", line 255, in update
    "includeEvents":            includeEvents,
  File "C:\Program Files (x86)\Python\Python35-32\lib\site-packages\ecobee\__init__.py", line 445, in get
    self._handle_error(r)
  File "C:\Program Files (x86)\Python\Python35-32\lib\site-packages\ecobee\__init__.py", line 491, in _handle_error
    raise EcobeeException(errmsg)
ecobee.EcobeeException: 9: Invalid selection. No thermostats in selection. Ensure permissions and selection.
```

Furthermore the following code snippet does return `thermostatIds` so I should be properly connected via the ecobee API.

``` python
eapi = ecobee.Client(APIKEY,scope='smartRead')
summary = eapi.thermostatSummary()
```

**Comment by jdrews** [comment]
I modified `__init.py__` to just list "registered" thermostats. Now I get actual data. 

`__init__.py` line 247

``` python
        data = self.get("thermostat", {
            "selection": {
                "selectionType":  "registered",
                "selectionMatch": "",
```
