### ISSUE TITLE
Did not import on python 2.7.10

### ISSUE THREAD

**Issue by gdbassett** [alertedsnake/python-ecobee#3]
I know it's not build for python 2 so no worries about fixing, but just wanted to drop a note that it didn't import on python 2.7.10 with the error:

```
  File "/usr/local/lib/python2.7/site-packages/ecobee/__init__.py", line 451
    raise EcobeeException("Connection error: {}".format(e)) from None
```

**Comment by alertedsnake** [comment]
Thanks, but I'm not interested in supporting legacy Python at this point.  I would expect more than this to break.

**Comment by gdbassett** [comment]
I completely understand though you may want to change the readme to indicate that you know it does not import under 2.7.10.

**Comment by alertedsnake** [comment]
Yep, I just did that.  Thanks.

**Comment by gdbassett** [comment]
you're welcome.  Thank you for the tool.
